node('fargate') {
   def commit_id
   stage('Checkout') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"
     commit_id = readFile('.git/commit-id').trim()
   }
   try{
    stage('Build') {
     def myTestContainer = docker.image('node:16')
     myTestContainer.pull()
     myTestContainer.inside {
       sh 'node --version'
     }
    }
   
    stage('Final'){
        echo 'Pipeline complete'
    }
   }catch(e){
     

      //thow error
      throw e
   }
   
                               
}                                          
